parameters:
    # maybe put this into the database later
    retromat.plan.titles:
        en:
            sequence_of_groups:
                0: [0, 1, 2, 4, 5, 6, 7] # how to encode that some groups may be skipped? Maybe include "" inside the group?
            groups_of_terms:
                0: ["Agile", "Scrum", "Kanban", "XP", "Extreme Programming", "Project", "Program", "Over All" ]
                1: ["Iteration", "Sprint", "Release", "Team", "Process"]
                2: ["Retrospective", "Retro", "Post Mortem", "A3"]
                3: ["Meeting", "Event", "Discussion"]
                4: ["Plan", "Guide", "Agenda"]
                5: ["Example", "Examples", "Activities"]
                6: ["with", "containing", "including"]
                7: ["5 Activities", "5 Stages", "5 Steps"]

                # Titles should have 50-60 characters https://moz.com/learn/seo/title-tag

                # more ideas, where could they fit?

                # Scaled , Large Scale

                # Scrum Tool(s)

                # Be Inspired while you ...
                # Plan, Organize, Create, Discover, Find, Be Inspired while ...

                # set the stage
                # gather data
                # generate insight
                # decide what to do
                # close the retrospective
                # something completely different

                # with
                # using

                8: ["CURRENT_PLAN_ID"] # how to encode this properly?
        de:
            groups_of_terms:
                0: ["Qualitätszirkel"]
