# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    array_to_object_mapper:
        class: AppBundle\Importer\ArrayToObjectMapper
    retromat.activity_by_phase:
        class: AppBundle\Activity\ActivityByPhase
        arguments: ["@doctrine.orm.entity_manager"]
    retromat.activity_reader:
        class: AppBundle\Importer\Activity\ActivityReader
        arguments: ["%kernel.root_dir%/../web/static/lang/activities_en.js"]
    retromat.activity_importer:
        class: AppBundle\Importer\Activity\ActivityImporter
        arguments: ["@doctrine.orm.entity_manager", "@retromat.activity_reader", "@array_to_object_mapper", "@validator"]
    retromat.color_varation:
        class: AppBundle\Twig\ColorVariation
    retromat.plan.plan_generator:
        class: AppBundle\Plan\PlanGenerator
        arguments: ["@retromat.plan.plan_id_generator", "@doctrine.orm.entity_manager"]
    retromat.plan.plan_id_generator:
        class: AppBundle\Plan\PlanIdGenerator
        arguments: ["@retromat.activity_by_phase"]
    retromat.plan.title_id_chooser:
        class: AppBundle\Plan\TitleIdChooser
        arguments: ["%retromat.plan.titles%"]
    retromat.plan.title_id_generator:
        class: AppBundle\Plan\TitleIdGenerator
        arguments: ["%retromat.plan.titles%"]
    retromat.plan.title_renderer:
        class: AppBundle\Twig\Title
        arguments: ["%retromat.plan.titles%"]
    retromat.sitemap.plan_generator:
        class: AppBundle\Sitemap\PlanGenerator
        arguments: ["@router", '@retromat.plan.plan_id_generator']
    retromat.sitemap.populate_subscriber:
        class: AppBundle\EventListener\SitemapPopulateSubscriber
        arguments: ["@router", "@doctrine.orm.entity_manager", "@retromat.sitemap.plan_generator", "@retromat.activity_by_phase"]
        tags:
            - { name: "kernel.event_subscriber" }