language: php

php:
    - 5.6
    - 7.0
    - 7.1

before_install:
    - cp backend/app/config/parameters.yml.travis backend/app/config/parameters.yml

install:
    - composer install --working-dir=backend

before_script:
    - php backend/bin/console doctrine:database:create --env=test
    - php backend/bin/console doctrine:schema:create --env=test
    - php backend/bin/console doctrine:fixtures:load -n --env=test

script:
    - phpunit -c backend

before_deploy:
    - php backend/bin/console cache:clear --env=prod
    - openssl aes-256-cbc -d -a -in .travis/rsa_travis_timon.enc -out .travis/rsa_travis_timon -k $rsa_travis_timon_phrase
    - chmod 600 .travis/rsa_travis_timon
    - eval "$(ssh-agent -s)"
    - ssh-add .travis/rsa_travis_timon
    - rm -rf .travis/

deploy:
    on:
        branch: travis
        condition: $TRAVIS_PHP_VERSION = 5.6
    skip_cleanup: true
    provider: script
    script:
        chmod u+w ~/.ssh/known_hosts ;
        echo 'vega.uberspace.de,95.143.172.245 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO7dYaOcJGBeXhHMG6AflOnZVNnm8iJn/qVwDcbcLjWJ' >> ~/.ssh/known_hosts ;
        echo 'vega.uberspace.de,2001:1a50:11::5f:8f:ac:f5 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO7dYaOcJGBeXhHMG6AflOnZVNnm8iJn/qVwDcbcLjWJ' >> ~/.ssh/known_hosts ;
        ssh timon@vega.uberspace.de "touch ~/travis-touched" ;
        curl -k "https://scrum.berlin/retromat/log.php?commit=$TRAVIS_COMMIT&line=deploy-last"

notifications:
    on_success: always
    on_failure: always
    email:
        recipients:
            - timon.fiddike@agile.coach
